---
- name: Install snapd
  ansible.builtin.apt:
    name: snapd
    state: present

- name: Install Microk8s
  community.general.snap:
    name: microk8s
    classic: true
    channel: "{{ microk8s_version }}"

- name: Add current user to group 'microk8s'
  ansible.builtin.user:
    name: "{{ ansible_facts['ansible_user_id'] }}"
    group: microk8s

- name: Recursively change ownership of ~/.kube
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    recurse: yes
    owner: "{{ ansible_facts['ansible_user_id'] }}"

- name: Add kubectl alias
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "alias kubectl='microk8s kubectl'"
